/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CERTIFICATES;


public class residency extends javax.swing.JFrame {

    /**
     * Creates new form clearance
     */
    public residency() {
        initComponents();
    }

    // Setter methods to set label texts dynamically
    public void setName(String text) {
        name.setText(text);
    }

    public void setPurok(String text) {
        purok.setText(text);
    }

    public void setBrgyCaptani(String text) {
        brgycaptani.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        residencypanel = new javax.swing.JPanel();
        brgycaptani = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        purok = new javax.swing.JLabel();
        clearanceimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        residencypanel.setBackground(new java.awt.Color(255, 255, 255));
        residencypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brgycaptani.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        brgycaptani.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brgycaptani.setText("Baranggay Captain");
        residencypanel.add(brgycaptani, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 170, 20));

        name.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("name");
        residencypanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 20));

        purok.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        purok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purok.setText("date");
        residencypanel.add(purok, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, 20));

        clearanceimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CERTIFICATES/residency (2).png"))); // NOI18N
        residencypanel.add(clearanceimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(residencypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 1060));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(residency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(residency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(residency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(residency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new residency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brgycaptani;
    private javax.swing.JLabel clearanceimage;
    private javax.swing.JLabel name;
    private javax.swing.JLabel purok;
    public javax.swing.JPanel residencypanel;
    // End of variables declaration//GEN-END:variables
}
