
package CITIZEN;

import CITIZEN.*;
import ADMIN.*;
import ADMIN.accountDetails1;
import BDR.loginForm;
import CITIZEN.changePass1;
import ADMIN.createUserForm;
import Config.Session;
import java.awt.Color;
import BDR.*;
import BDR.dashBoardPage;
import BDR.settingsPage;
import config.config;
import Config.passwordHasher;
import java.awt.Window;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;



public class changePass1 extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public changePass1() {
        initComponents();
    }
    Color navcolor = new Color(41,50,57);  
    Color headcolor = new Color(137,207,24); 
    Color bodycolor = new Color(110,177,214);

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        p_add = new javax.swing.JPanel();
        ADD1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cfname = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        clname = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        save = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();

        p_add.setBackground(new java.awt.Color(41, 50, 57));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        ADD1.setBackground(new java.awt.Color(44, 71, 35));
        ADD1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ADD1.setForeground(new java.awt.Color(255, 255, 255));
        ADD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADD1.setText("ADD");
        p_add.add(ADD1);
        ADD1.setBounds(0, 10, 160, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(123, 181, 104));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navbar.setBackground(new java.awt.Color(41, 50, 57));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_Folder/user-logo.png"))); // NOI18N
        navbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 90));

        cfname.setBackground(new java.awt.Color(44, 71, 35));
        cfname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cfname.setForeground(new java.awt.Color(255, 255, 255));
        cfname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cfname.setText("USER");
        navbar.add(cfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 20));

        user_name.setBackground(new java.awt.Color(44, 71, 35));
        user_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_name.setText("CURRENT USER ID:");
        navbar.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 160, 28));

        acc_id.setBackground(new java.awt.Color(44, 71, 35));
        acc_id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        acc_id.setForeground(new java.awt.Color(255, 255, 255));
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("Account ID");
        navbar.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 160, 28));

        clname.setBackground(new java.awt.Color(44, 71, 35));
        clname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clname.setForeground(new java.awt.Color(255, 255, 255));
        clname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clname.setText("USER");
        navbar.add(clname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 20));

        back.setBackground(new java.awt.Color(41, 50, 57));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Back");
        back.add(jLabel4);
        jLabel4.setBounds(50, 10, 60, 20);

        navbar.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 160, 43));

        save.setBackground(new java.awt.Color(41, 50, 57));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Change Password");
        save.add(jLabel3);
        jLabel3.setBounds(10, 10, 140, 20);

        navbar.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 43));

        jPanel2.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 420));

        header.setBackground(new java.awt.Color(137, 207, 241));

        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        maximize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        maximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximize.setText("—");
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHANGE PASSWORD");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 158, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(maximize))
                .addGap(0, 28, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 710, 50));

        maindesktop.setBackground(new java.awt.Color(110, 177, 214));
        maindesktop.setPreferredSize(new java.awt.Dimension(760, 420));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel2.add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 710, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_maximizeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess = Session.getInstance();
        
        if(sess.getUid()== 0){
            JOptionPane.showMessageDialog(null, " No Account, Log In First!");
            loginForm lf = new loginForm();
            lf.setVisible(true);
            this.dispose();            
        }else{
               acc_id.setText(""+sess.getUid());
               cfname.setText(""+sess.getFname());
               clname.setText(""+sess.getLname());
              
               
        } 
    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        createUserForm cuf = new createUserForm();
        cuf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_addMouseClicked

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
        p_add.setBackground(bodycolor);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
        p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
       
           
try {
    config cdb = new config();
    Session sess = Session.getInstance();

    if (sess.getUid() <= 0) { 
        JOptionPane.showMessageDialog(null, "Invalid session. Please log in again.");
        
        loginForm l = new loginForm();
        l.setVisible(true);
        this.dispose();
    }

    String query = "SELECT pname FROM users WHERE id = ?";
    PreparedStatement stmt = cdb.getConnection().prepareStatement(query);
    stmt.setInt(1, sess.getUid()); 

    ResultSet rs = stmt.executeQuery();

    if (rs.next()) {
        String storedHashedPassword = rs.getString("pname");

        String oldPassword = JOptionPane.showInputDialog("Enter current password:");
        String newPassword = JOptionPane.showInputDialog("Enter new password:");
        String confirmPassword = JOptionPane.showInputDialog("Confirm new password:");

        if (oldPassword == null || newPassword == null || confirmPassword == null || 
            oldPassword.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password fields cannot be empty!");
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Passwords do not match! Please try again.");
            return;
        }

        if (!passwordHasher.checkPassword(oldPassword, storedHashedPassword)) {
            JOptionPane.showMessageDialog(null, "Incorrect old password!");
            return;
        }

        if (passwordHasher.checkPassword(newPassword, storedHashedPassword)) {
            JOptionPane.showMessageDialog(null, "You cannot use your old password as the new password. Please choose a different one.");
            return;
        }

        String hashedNewPassword = passwordHasher.hashPassword(newPassword);

        String updateQuery = "UPDATE users SET pname = ? WHERE id = ?";
        PreparedStatement updateStmt = cdb.getConnection().prepareStatement(updateQuery);
        updateStmt.setString(1, hashedNewPassword);
        updateStmt.setInt(2, sess.getUid());

        int rowsUpdated = updateStmt.executeUpdate();
        updateStmt.close();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Password changed successfully!");

            Window currentWindow = SwingUtilities.getWindowAncestor(JOptionPane.getRootFrame());
            if (currentWindow != null) {
                currentWindow.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update password!");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No account found for the given ID.");
    }

    rs.close();
    stmt.close();
    cdb.closeConnection();

} catch (SQLException ex) {
    System.out.println("SQL Error: " + ex.getMessage());
} catch (Exception ex) { 
    Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_saveMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
      new accountDetails1().setVisible(true);this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(Color.white);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color (41,50,57));
    }//GEN-LAST:event_backMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADD1;
    private javax.swing.JLabel acc_id;
    private javax.swing.JPanel back;
    private javax.swing.JLabel cfname;
    private javax.swing.JLabel clname;
    private javax.swing.JLabel close;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JDesktopPane maindesktop;
    private javax.swing.JLabel maximize;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel save;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
